# Generated by Django 3.2.4 on 2024-09-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
